name: money_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  flutter_speed_dial: ^7.0.0
  gap: ^3.0.1
  google_fonts: ^8.0.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/wallet_add_white.png
    - assets/image/wallet_withdraw_white.png
